from crm.database import fetch_all, insert_record, now_str
from crm.services import next_revision_number, save_account, save_activity, save_opportunity, save_proposal


def seed_if_empty():
    if not fetch_all("accounts").empty:
        return
    a1 = save_account({"name": "Braskem", "segment": "Petroquímico / Químico", "cnpj": "", "site": "https://www.braskem.com.br", "main_unit": "Camaçari", "strategic_status": "Conta estratégica", "notes": "Conta com histórico de aditivos e projetos multidisciplinares."})
    a2 = save_account({"name": "PRIO", "segment": "Óleo & Gás / Offshore / Onshore", "cnpj": "", "site": "https://www.prio3.com.br", "main_unit": "FORTE / FRADE", "strategic_status": "Conta estratégica", "notes": "Conta relevante para offshore, revisão documental e utilidades."})
    a3 = save_account({"name": "Energia Sul", "segment": "Energia", "cnpj": "", "site": "", "main_unit": "UTE Alpha", "strategic_status": "Prospect", "notes": "Conta alvo para modernização e EVTE."})
    opp1 = save_opportunity({"opportunity_name": "FM 0194 – Enc Desc SVs", "internal_code": "SAN-2026-001", "account_id": a1, "unit_asset": "Unidade PE", "segment": "Petroquímico / Químico", "lead_source": "Cliente recorrente", "service_type": "Projeto básico", "main_discipline": "Processos", "involved_disciplines": "Processos, Tubulação, Instrumentação, Elétrica", "nature": "Aditivo", "project_phase": "Básico", "location_type": "Onshore", "scope_summary": "Adequação de sistema com revisão de documentos e suporte técnico multidisciplinar.", "client_objective": "Atualizar base técnica e viabilizar continuidade do investimento.", "key_deliverables": "Critérios de projeto, memória descritiva, LD, revisão de desenhos, PATEC.", "critical_assumptions": "Cliente disponibilizar documentos base, visitas e interfaces com operação.", "information_gaps": "Lista mestre do cliente pendente de consolidação.", "needs_site_visit": 1, "needs_technical_meeting": 1, "needs_nda": 0, "needs_contract_draft": 1, "needs_registration": 1, "estimated_value": 480000, "estimated_hh": 2200, "target_margin": 32, "probability": 85, "proposal_deadline": "2026-03-15", "execution_deadline": "2026-06-30", "commercial_owner": "Comercial", "proposal_owner": "Engenharia", "technical_coordinator": "Engenharia", "approving_director": "Diretoria", "next_step": "Fechar última rodada de negociação técnica.", "next_step_date": "2026-03-10", "current_blocker": "Validação da minuta contratual.", "mapped_competitor": "Concorrente A", "loss_reason": "", "stage": "Em negociação", "go_no_go_status": "Go", "risk_level": "Médio"})
    opp2 = save_opportunity({"opportunity_name": "Inj Fluido FORTE", "internal_code": "SAN-2026-002", "account_id": a2, "unit_asset": "FPSO FORTE", "segment": "Óleo & Gás / Offshore / Onshore", "lead_source": "Relacionamento comercial", "service_type": "Projeto detalhado", "main_discipline": "Tubulação", "involved_disciplines": "Tubulação, Mecânica, Elétrica, Instrumentação, Automação", "nature": "Novo", "project_phase": "Detalhado", "location_type": "Offshore", "scope_summary": "Projeto para melhorias em sistema de injeção de fluido com revisão de P&IDs.", "client_objective": "Melhorar confiabilidade operacional e atualizar documentação.", "key_deliverables": "P&IDs, especificações, listas, memoriais, pareceres.", "critical_assumptions": "Recebimento de documentos do ativo e liberação para visitas offshore.", "information_gaps": "TR em revisão.", "needs_site_visit": 1, "needs_technical_meeting": 1, "needs_nda": 1, "needs_contract_draft": 1, "needs_registration": 0, "estimated_value": 780000, "estimated_hh": 3600, "target_margin": 35, "probability": 60, "proposal_deadline": "2026-03-20", "execution_deadline": "2026-08-15", "commercial_owner": "Comercial", "proposal_owner": "Engenharia", "technical_coordinator": "Engenharia", "approving_director": "Diretoria", "next_step": "Consolidar HH e versão R1 da proposta.", "next_step_date": "2026-03-12", "current_blocker": "Falta de FE preliminar do cliente.", "mapped_competitor": "Concorrente B", "loss_reason": "", "stage": "Em elaboração de proposta", "go_no_go_status": "Go", "risk_level": "Alto"})
    save_opportunity({"opportunity_name": "EVTE Modernização UTE Alpha", "internal_code": "SAN-2026-003", "account_id": a3, "unit_asset": "UTE Alpha", "segment": "Energia", "lead_source": "Indicação", "service_type": "EVTE", "main_discipline": "Processos", "involved_disciplines": "Processos, Elétrica, Instrumentação, Civil", "nature": "Novo", "project_phase": "Estudo / EVTE", "location_type": "Onshore", "scope_summary": "Estudo de viabilidade técnica e econômica para modernização de utilidades.", "client_objective": "Definir alternativa com melhor CAPEX/OPEX e prazo.", "key_deliverables": "EVTE, parecer técnico, CAPEX/OPEX, recomendações.", "critical_assumptions": "Dados operacionais devem ser disponibilizados pelo cliente.", "information_gaps": "Sem cronograma-base do cliente.", "needs_site_visit": 0, "needs_technical_meeting": 1, "needs_nda": 1, "needs_contract_draft": 0, "needs_registration": 0, "estimated_value": 210000, "estimated_hh": 900, "target_margin": 30, "probability": 35, "proposal_deadline": "2026-03-28", "execution_deadline": "2026-05-30", "commercial_owner": "Comercial", "proposal_owner": "Engenharia", "technical_coordinator": "Engenharia", "approving_director": "Diretoria", "next_step": "Solicitar dados operacionais e reunião técnica.", "next_step_date": "2026-03-11", "current_blocker": "Dados do ativo não recebidos.", "mapped_competitor": "", "loss_reason": "", "stage": "Entendimento do escopo", "go_no_go_status": "Em análise", "risk_level": "Médio"})
    save_proposal({"opportunity_id": opp1, "revision_number": next_revision_number(opp1), "version_label": "R1", "proposal_value": 470000, "sent_date": "2026-02-27", "validity_days": 30, "execution_deadline": "2026-06-30", "status": "Enviada", "objective_text": "Adequar documentação e suportar engenharia multidisciplinar do ativo.", "service_description": "Desenvolvimento de engenharia com revisão documental, pareceres e apoio técnico.", "assumptions_text": "Cliente disponibilizar documentos, acessos e aprovações em tempo hábil.", "exclusions_text": "Sem fornecimento, montagem, obra, manutenção operacional ou comissionamento executivo.", "deliverables_text": "Critérios, memoriais, LD, revisão de desenhos, pareceres.", "hh_summary": "Eng. Sênior, Pleno, Projetista e apoio gráfico.", "pricing_notes": "Valor fechado com base em HH e PPU interna."})
    save_activity({"related_type": "opportunity", "related_id": opp1, "activity_type": "Jurídico / minuta", "description": "Validar ajustes da minuta antes do fechamento.", "owner": "Jurídico", "due_date": "2026-03-08", "status": "Aberta"})
    save_activity({"related_type": "opportunity", "related_id": opp2, "activity_type": "Revisão de proposta", "description": "Fechar HH multidisciplinar e premissas técnicas.", "owner": "Engenharia", "due_date": "2026-03-09", "status": "Em andamento"})
    items = [("Premissas", "Premissa padrão de documentação", "Cliente fornecerá TR, RFQ, FE e documentos base necessários para elaboração da proposta."), ("Fora de escopo", "Exclusão padrão de execução", "Não inclui fornecimento, aquisição, montagem, obra, instalação, manutenção operacional ou comissionamento executivo."), ("Modelo de proposta", "Estrutura padrão", "Objetivo do escopo; descrição dos serviços; premissas; fora de escopo; LD; composição comercial; cronograma; validade."), ("Lista de documentos", "LD básica - engenharia", "Lista de documentos deve refletir fase do projeto e aderência real ao escopo do cliente."), ("Caso semelhante", "Braskem - revisão documental", "Caso com atualização de documentos, as built e parecer técnico multidisciplinar."), ("Compliance", "Regra de posicionamento", "A SANDECH é consultoria de engenharia; não deve ser posicionada como executora de obra, montagem ou fornecimento." )]
    for category, title, content in items:
        insert_record("library_items", {"category": category, "title": title, "content": content, "created_at": now_str(), "updated_at": now_str()})
